services:
  caddy:
    container_name: caddy-azure-dns
    image: ghcr.io/lorna-jane-it/caddy-azure-dns:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - TZ=Australia/Brisbane
      - AZURE_TENANT_ID=abcdefghijklmnopqrstuvwxyz
      - AZURE_CLIENT_ID=abcdefghijklmnopqrstuvwxyz
      - AZURE_CLIENT_SECRET="abcdefghijklmnopqrstuvwxyz"
      - AZURE_SUBSCRIPTION_ID=abcdefghijklmnopqrstuvwxyz
      - AZURE_RESOURCE_GROUP_NAME=abcdefghijklmnopqrstuvwxyz
    volumes:
      - /docker-data-path/Caddyfile:/etc/caddy/Caddyfile
      - /docker-data-path/data:/data
      - /docker-data-path/config:/config