services:
  caddy:
    container_name: caddy-azure-dns
    image: caddy-azure-dns
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - TZ=Australia/Brisbane
      - AZURE_TENANT_ID=abcdefghijklmnopqrstuvwxyz
      - AZURE_CLIENT_ID=abcdefghijklmnopqrstuvwxyz
      - AZURE_CLIENT_SECRET=/run/secrets/azure_client_secret
      - AZURE_SUBSCRIPTION_ID=abcdefghijklmnopqrstuvwxyz
      - AZURE_RESOURCE_GROUP_NAME=abcdefghijklmnopqrstuvwxyz
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /docker-data-path/data:/data
      - /docker-data-path/config:/config
    secrets:
      - azure_client_secret
secrets:
  azure_client_secret:
    file: ./azure_client_secret.txt