services:
  caddy:
    container_name: caddy-azure-dns
    image: ghcr.io/lorna-jane-it/caddy-azure-dns:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - TZ=${TZ:-Australia/Brisbane}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID:?error}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID:?error}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:?error}
      - AZURE_SUBSCRIPTION_ID=${AZURE_SUBSCRIPTION_ID:?error}
      - AZURE_RESOURCE_GROUP_NAME=${AZURE_RESOURCE_GROUP_NAME:?error}
    volumes:
      - /docker-data-path/Caddyfile:/etc/caddy/Caddyfile
      - /docker-data-path/data:/data
      - /docker-data-path/config:/config