name: main Pull

on:
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-main-pull:
    name: Test Build on 'main' Pull
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Lowercase REGISTRY
        run: |
          echo "REGISTRY_LC=${REGISTRY@L}" >> ${GITHUB_ENV}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_LC }}/${{ env.IMAGE_NAME }}

      - name: Build for testing
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: ${{ env.REGISTRY_LC }}/${{ env.IMAGE_NAME }}:test

      - name: Test build
        run: |
          docker run --rm ${{ env.REGISTRY_LC }}/${{ env.IMAGE_NAME }}:test /bin/sh -c "caddy version; caddy list-modules; caddy environ;"